version: '1'
networks:
  product:
    name: product_network

services:
  product_embedding1:
    container_name: product_embedding1
    image: tensorflow/serving:latest
    networks:
      - product
    environment:
      - MODEL_NAME=embedding
    volumes:
      - ${PWD}/data/models/embedding:/models/embedding:ro
  product_embedding2:
    container_name: product_embedding2
    image: tensorflow/serving:latest
    networks:
      - product
    environment:
      - MODEL_NAME=embedding
    volumes:
      - ${PWD}/data/models/embedding:/models/embedding:ro
  nginx:
    container_name: product_nginx
    image: nginx:latest
    depends_on:
      - product_embedding1
      - product_embedding2
    networks:
      - product
    ports:
      - 8501:8501
    volumes:
      - ${PWD}/deployment/nginx/embedding.conf:/etc/nginx/conf.d/embedding.conf
  redis:
    container_name: product_redis
    image: redis:latest
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    networks:
      - product
    volumes:
      - ${PWD}/data/redis:/data
    ports:
      - 6379:6379
  elasticsearch:
    container_name: product_elasticsearch
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ${PWD}/data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

    networks:
      - product
  product_app:
    image: product_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_app
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_SEARCH_INDEX=search-my-search-embedding
      - SEARCH_API_KEY=${SEARCH_API_KEY}
      - EMBEDDING_SERVICE_HOST=http://nginx:8501
      - EMBEDDING_SERVICE_HOST_MODEL_NAME=embedding
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATELIMIT_DURATION=5s
      - RATELIMIT_COUNT=10

    ports:
      - 8088:80
    networks:
      - product
    depends_on:
      - elasticsearch
      - redis
      - nginx
